version: '3'

services:
  fisioPlanDB:
    image: postgres:16.3
    container_name: fisioplan
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data